### ISSUE TITLE
relion_python_tomo_import :: mdocfil // pydantic dependencies version conflicts

### ISSUE THREAD

**Issue by EricDeveaud** [3dem/relion#1111]
Hello, 

I was asked to install relionv5.0 (I know it is currently in beta stage) 
installation wen smoothly, and I ran a basic test suite, ie more or less each installed binary --help, as a starting point.

**Describe your problem**
```
build-nv [rpm]:relion/relion-5.0.0 > relion_python_tomo_import --help
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/gensoft/exe/relion/5.0.0/venv/lib/python3.10/site-packages/tomography_python_programs/import_tilt_series/__init__.py", line 1, in <module>
    from .serialem import import_tilt_series_from_serial_em
  File "/opt/gensoft/exe/relion/5.0.0/venv/lib/python3.10/site-packages/tomography_python_programs/import_tilt_series/serialem.py", line 5, in <module>
    import mdocfile
ModuleNotFoundError: No module named 'mdocfile'
```

however when I try to install mdocfile mdoule.  it removes current pydantic module (pydantic-1.10.15) and install pydantic-2.7.0
pip complains about dependencies conflicts.

```
morphosamplers 0.0.11 requires pydantic<2, but you have pydantic 2.7.0 which is incompatible.
napari 0.4.18 requires pydantic<2,>=1.9.0, but you have pydantic 2.7.0 which is incompatible.
```

and in facts it breaks `relion_python_tomo_exclude_tilt_images`, `relion_python_tomo_get_particle_poses`, `relion_python_tomo_pick`, `relion_python_tomo_view`.

**DO NOT** cross post a same question to multiple issues and/or many mailing lists (CCPEM, 3DEM, etc).

**Environment:**
 - OS: 
 ```
 NAME="Red Hat Enterprise Linux"
VERSION="8.8 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.8 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.8
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"
```

 - MPI runtime: `OpenMPI 4.0.5`
 - RELION version v5 commit: a0b145a715b7b3c524bedc074687de06cc9a4ee8
 - Memory: `free --giga`: 540`
 - GPU: `Quadro RTX 5000a
 - Pytghon version: `Python 3.10.7`

NB as a side note: `m`ke install` does not install `src/tomography_python_programs/` to python site-packages I had to cpy it manually.

hope this will help

regards

Eric

**Comment by EricDeveaud** [comment]
OK after diving in the conda environnement I found that 
installation of 
```
morphosamplers==0.0.11 
mdocfile==0.0.8
pydantic==1.10.15
```

fixes the conflict problem.

regards

Eric
