### ISSUE TITLE
relion 5 pick tomograms: RuntimeError: no validator found for <class 'numpy.ndarray'>, see `arbitrary_types_allowed` in Config

### ISSUE THREAD

**Issue by RichStone99** [3dem/relion#1194]
Installed current relion 5 on centOS 9. Am trying the subtomogram averaging tutorial with the HIV VLP data set. Worked well up to "Reconstruct tomograms". Tomograms have been generated and look fine. But when trying to launch "Pick tomograms", napari didn't open and got the following error message. How can we fix it? Seems to relate to pydantic and/or tomography_python_programs.
Btw, napari ran well during, for example, the "Exclude tilt-images" step and inspection of generated tomo in the "Reconstruct tomograms" step. IMOD was used in "Reconstruct tomograms".

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tangl/sw/miniforge3/envs/relion-5.0/lib/python3.10/site-packages/tomography_python_programs/pick/__init__.py", line 1, in <module>
    from .particles import pick_particles
  File "/home/tangl/sw/miniforge3/envs/relion-5.0/lib/python3.10/site-packages/tomography_python_programs/pick/particles.py", line 7, in <module>
    from napari_threedee.annotators import PointAnnotator
  File "/home/tangl/sw/miniforge3/envs/relion-5.0/lib/python3.10/site-packages/napari_threedee/__init__.py", line 1, in <module>
    from . import data_models
  File "/home/tangl/sw/miniforge3/envs/relion-5.0/lib/python3.10/site-packages/napari_threedee/data_models/__init__.py", line 1, in <module>
    from .points import N3dPoints
  File "/home/tangl/sw/miniforge3/envs/relion-5.0/lib/python3.10/site-packages/napari_threedee/data_models/points.py", line 8, in <module>
    from napari_threedee.annotators.base import N3dDataModel
  File "/home/tangl/sw/miniforge3/envs/relion-5.0/lib/python3.10/site-packages/napari_threedee/annotators/__init__.py", line 5, in <module>
    from .surfaces import SurfaceAnnotator
  File "/home/tangl/sw/miniforge3/envs/relion-5.0/lib/python3.10/site-packages/napari_threedee/annotators/surfaces/__init__.py", line 1, in <module>
    from .annotator import SurfaceAnnotator
  File "/home/tangl/sw/miniforge3/envs/relion-5.0/lib/python3.10/site-packages/napari_threedee/annotators/surfaces/annotator.py", line 12, in <module>
    from morphosamplers.surface_spline import GriddedSplineSurface
  File "/home/tangl/sw/miniforge3/envs/relion-5.0/lib/python3.10/site-packages/morphosamplers/__init__.py", line 12, in <module>
    from morphosamplers.models import Path, Sphere, Surface, Dipole
  File "/home/tangl/sw/miniforge3/envs/relion-5.0/lib/python3.10/site-packages/morphosamplers/models/__init__.py", line 1, in <module>
    from .path import Path
  File "/home/tangl/sw/miniforge3/envs/relion-5.0/lib/python3.10/site-packages/morphosamplers/models/path.py", line 7, in <module>
    class Path(MorphoModel):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 504, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 434, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 555, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 829, in pydantic.fields.ModelField.populate_validators
  File "pydantic/validators.py", line 765, in find_validators
RuntimeError: no validator found for <class 'numpy.ndarray'>, see `arbitrary_types_allowed` in Config

**Comment by labzw** [comment]
Having exactly the same error. I feel this might be a bug in _morphosamplers_. It seems natively Pydantic does not support ndarray.

Solved or bypassed this issue by adding 
```
class Config:
        arbitrary_types_allowed = True
```
in `dipole.py` `path.py` `sphere.py` `surface.py` files under /YOUR/CONDA/PATH/envs/relion-5.0/lib/python3.10/site-packages/morphosamplers/models

**Comment by alisterburt** [comment]
@RichStone99 @labzw apologies for this - could you please run `pip show morphosamplers` and `pip show pydantic` in your RELION 5 conda environment and tell me the output? We recently moved to only supporting `pydantic>=2` which may be the root cause of this issue for you

**Comment by CACNYC** [comment]
@alisterburt I have an identical error to @RichStone99 @labzw :
Traceback (most recent call last):
File "<string>",
, line 1, in < module»
File "/opt/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/tomography_python_programs/pick/_init_py", line 1, in <module> from particles import pick_particles
File "/opt/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/tomography_python_programs/pick/particles.py", line 7, in <module> from napari_threedee.annotators import PointAnnotator
File "/opt/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/napari_threedee/_init_.py", line 1, in <module> from. import data models
File "/opt/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/napari_threedee/data_models/_init_py", line 1, in <module> from points import N3dPoints
File "/opt/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/napari_threedee/data_models/points.py", line 8, in <module> from napari threedee.annotators.base import N3dDataModel
File "/opt/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/napari_threedee/annotators/_init.py", line 5, in <module>
from surfaces import SurfaceAnnotator
File "/opt/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/napari_threedee/annotators/surfaces/_init_py", line 1, in < module> from annotator import SurfaceAnnotator
File "/opt/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/napari_threedee/annotators/surfaces/annotator.py", line 12, in <module> from morphosamplers.surface_spline import GriddedSplineSurface
File "/opt/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/morphosamplers/_init_py", line 12, in <module > from morphosamplers.models import Path, Sphere, Surface, Dipole
File "/opt/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/morphosamplers/models/_init_py", line 1, in <module> from path import Path
File "/opt/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/morphosamplers/models/path.py", line 7, in <module> class Path(MorphoModel):
File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass._new_ File "pydantic/fields.py", line 504, in pydantic.fields.ModelField.infer File "pydantic/fields.py", line 434, in pydantic.fields.ModelField.__init File "pydantic/fields.py", line 555, in pydantic.fields.ModelField prepare File "pydantic/fields.py", line 829, in pydantic.fields.ModelField.populate_validators File "pydantic/validators.py", line 765, in find_validators
RuntimeError: no validator found for <class 'numpy.ndarray >, see 'arbitrary_types_allowed* in Config

Output of pip show morphosamplers:
(relion-5.0) [spuser@spgpu TS_01_ projecti$ pip show morphosamplers
Name: morphosamplers
Version: 0.0.15
Summary: A library for sampling image data along morphological objects such as splines and surfaces.
Home-page: https: //github.com/kevinyamauchi/morphosamplers
Author: Kevin Yamauchi
Author-email: kevin.yamauchi@gmail.com
License: BSD 3-Clause License
Location: /opt/miniconda3/envs/relion-5.0/lib/python3.10/site-packages
Requires: einops, numpy, psygnal, pydantic, pydantic-compat, scipy, typing-extensions
•Required-by: napari-threedee, relion

Output of pip show pydantic:
(relion-5.0) [spuser@spgpu TS_01 projecti$ pip show pydantic
-Name: pydantic
Version: 1.10.18
Summary: Data validation and settings management using python type hints
Home-page: https: //github.com/pydantic/pydantic
rAuthor: Samuel Colvin
l Author-email: s@muelcolvin.com
License: MIT
Location: /opt/miniconda3/envs/relion-5.0/lib/python3.10/site-packages
Requires: typing-extensions
Required-by: app-model, mdocfile, morphosamplers, napari, napari-threedee, npez, pydantic-compat

Ah, then pydantic 1.x is the culprit?

Thanks for your help Alister!

**Comment by bogdantoader** [comment]
Hello, downgrading to the following versions in the conda environment should fix the issue:

>>> morphosamplers.__version__
'0.0.13'
>>> pydantic.__version__
'1.10.18'
>>> napari.__version__
'0.4.18'

**Comment by CACNYC** [comment]
> Hello, downgrading to the following versions in the conda environment should fix the issue:
> 
> > > > morphosamplers.**version**
> > > > '0.0.13'
> > > > pydantic.**version**
> > > > '1.10.18'
> > > > napari.**version**
> > > > '0.4.18'

Thanks Bogdan, I can confirm that rolling back morphosamplers to version 0.0.13, combined with pydantic 1.10.18 and napari 0.4.18, allowed both the Exclude tilt and Pick tomograms job types to run and complete successfully.

**Comment by labzw** [comment]
So after I rebuild the latest version and roll back morphosamplers to 0.0.13, I am getting this error now.......

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/bin/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/tomography_python_programs/exclude_tilt_images/__init__.py", line 1, in <module>
    from ._cli import cli
  File "/usr/bin/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/tomography_python_programs/exclude_tilt_images/_cli.py", line 8, in <module>
    from .relion_tilt_image_excluder import RelionTiltImageExcluderWidget
  File "/usr/bin/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/tomography_python_programs/exclude_tilt_images/relion_tilt_image_excluder.py", line 5, in <module>
    from .._qt.tilt_image_excluder import TiltImageExcluderWidget
  File "/usr/bin/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/tomography_python_programs/_qt/tilt_image_excluder.py", line 8, in <module>
    from .components.tilt_image_selection_widget import TiltImageSelectionWidget
  File "/usr/bin/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/tomography_python_programs/_qt/components/tilt_image_selection_widget.py", line 12, in <module>
    class TiltImageSelectionWidget(QWidget):
  File "/usr/bin/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/tomography_python_programs/_qt/components/tilt_image_selection_widget.py", line 17, in TiltImageSelectionWidget
    viewer: napari.Viewer,
  File "/usr/bin/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/napari/_lazy.py", line 45, in __getattr__
    submod = import_module(
  File "/usr/bin/miniconda3/envs/relion-5.0/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/bin/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/napari/viewer.py", line 8, in <module>
    from napari.components.viewer_model import ViewerModel
  File "/usr/bin/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/napari/components/__init__.py", line 19, in <module>
    from napari.components.layerlist import LayerList
  File "/usr/bin/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/napari/components/layerlist.py", line 9, in <module>
    from napari.layers import Layer
  File "/usr/bin/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/napari/layers/__init__.py", line 12, in <module>
    from napari.layers.points import Points
  File "/usr/bin/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/napari/layers/points/__init__.py", line 1, in <module>
    from napari.layers.points import _points_key_bindings
  File "/usr/bin/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/napari/layers/points/_points_key_bindings.py", line 4, in <module>
    from napari.layers.points.points import Points
  File "/usr/bin/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/napari/layers/points/points.py", line 38, in <module>
    from napari.layers.utils.text_manager import TextManager
  File "/usr/bin/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/napari/layers/utils/text_manager.py", line 29, in <module>
    class TextManager(EventedModel):
  File "/usr/bin/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/napari/layers/utils/text_manager.py", line 83, in TextManager
    string: StringEncoding = ConstantStringEncoding(constant='')
  File "/usr/bin/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/napari/utils/events/evented_model.py", line 242, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ConstantStringEncoding
constant
  Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword. (type=value_error)

```

**Comment by zzha25** [comment]
I installed relion5 and had following error  when I run pick tomograms.

"/home/barharbor/anaconda3/envs/relion-5.0/lib/python3.10/site-packages/morphosamplers/__init__.py", line 12, in <module>
    from morphosamplers.models import Path, Sphere, Surface, Dipole
  File "/home/barharbor/anaconda3/envs/relion-5.0/lib/python3.10/site-packages/morphosamplers/models/__init__.py", line 1, in <module>
    from .path import Path
  File "/home/barharbor/anaconda3/envs/relion-5.0/lib/python3.10/site-packages/morphosamplers/models/path.py", line 7, in <module>
    class Path(MorphoModel):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 504, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 434, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 555, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 829, in pydantic.fields.ModelField.populate_validators
  File "pydantic/validators.py", line 768, in find_validators
RuntimeError: no validator found for <class 'numpy.ndarray'>, see `arbitrary_types_allowed` in Config

**Comment by bogdantoader** [comment]
Hi @zzha25 , before I check further, can you please confirm that you have these versions of `morphosamplers`, `pydantic` and `napari` in your relion-5 conda environment?

> Hello, downgrading to the following versions in the conda environment should fix the issue:
> 
> > > > morphosamplers.**version**
> > > > '0.0.13'
> > > > pydantic.**version**
> > > > '1.10.18'
> > > > napari.**version**
> > > > '0.4.18'
