### ISSUE TITLE
Refine3D with --continue produces corrupt .mrc files

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#177]
Originally reported by: **Daniel Larsson (Bitbucket: [larsson](https://bitbucket.org/larsson), GitHub: [larsson](https://github.com/larsson))**

----------------------------------------

This is using Relion 2.0.2 (beta) compiled in single precision.

First I started a job with --gpu, which eventually crashed due to CUDA running out of memory. Then I wanted to --continue without GPU, starting from the iteration where the job crashed. The file run_ct16_it_016_half1_class001.mrc is ok, but any further iteration produces corrupt mrc files. I.e. when trying to open the file in Chimera, I get an error message (see message at the end).

I tried to restart with the continue flag three times and one timeI got one mrc a file that did not produce error messages in Chimera, but very strange looking data (only stuff in one quadrant of the box). One other time, one of the half-reconstructions looked fine, while the other produced corrupt mrc files.

Chimera Error (when trying to open a corrupt file):

Traceback (most recent call last):
  File "/Applications/Chimera.app/Contents/Resources/share/chimeraInit.py", line 683, in init
    chimera.openModels.open(a, prefixableType=1)
  File "/Applications/Chimera.app/Contents/Resources/share/chimera/__init__.py", line 1892, in open
    models = func(filename, *args, **kw)
  File "/Applications/Chimera.app/Contents/Resources/share/VolumeViewer/ChimeraExtension.py", line 43, in open_cb
    drlist = open_volume_file(path, ftype, open_models = False)
  File "/Applications/Chimera.app/Contents/Resources/share/VolumeViewer/volume.py", line 2710, in open_volume_file
    for g in glist]
  File "/Applications/Chimera.app/Contents/Resources/share/VolumeViewer/volume.py", line 2765, in volume_from_grid_data
    v.show()
  File "/Applications/Chimera.app/Contents/Resources/share/VolumeViewer/volume.py", line 692, in show
    self.show_surface(show, show_mesh, self.rendering_options)
  File "/Applications/Chimera.app/Contents/Resources/share/VolumeViewer/volume.py", line 705, in show_surface
    self.update_surface(show_mesh, rendering_options)
  File "/Applications/Chimera.app/Contents/Resources/share/VolumeViewer/volume.py", line 724, in update_surface
    self.update_surface_piece(level, rgba, show_mesh, ro, pieces[k])
  File "/Applications/Chimera.app/Contents/Resources/share/VolumeViewer/volume.py", line 785, in update_surface_piece
    if self.calculate_contour_surface(level, rendering_options, p):
  File "/Applications/Chimera.app/Contents/Resources/share/VolumeViewer/volume.py", line 885, in calculate_contour_surface
    tf = zero_translation(transpose_matrix(invert_matrix(transform)))
  File "/Applications/Chimera.app/Contents/Resources/share/Matrix/matrix.py", line 114, in invert_matrix
    rinv[:,:] = matrix_inverse(r)
  File "/Applications/Chimera.app/Contents/Resources/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 445, in inv
    return wrap(solve(a, identity(a.shape[0], dtype=a.dtype)))
  File "/Applications/Chimera.app/Contents/Resources/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 328, in solve
    raise LinAlgError('Singular matrix')
LinAlgError: Singular matrix
Error while processing /Users/larsson/wd/job1/relion/Refine3D/job061/run_ct15_it017_half2_class001.mrc:
LinAlgError: Singular matrix

  File "/Applications/Chimera.app/Contents/Resources/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 328, in solve
    raise LinAlgError('Singular matrix')

See reply log for Python traceback. 

----------------------------------------
- Bitbucket: https://bitbucket.org/tcblab/relion2-beta/issue/177

**Comment by bforsbe** [comment]
This issue should be fixed in v2.0.4, which only sets the corrupt header fields if they are finite. The fields which are "corrupt" are only in the mrc header (i.e. the volume-data is NOT corrupt), and not used by relion. The issue of persistence of corrupt volumes and their effect on the chimera environment in general has also been noted to the chimera development team.

**Comment by davboyer** [comment]
Hello,

I am using Relion 2.1 beta-1 and I believe I have the same problem. The volume after the first 20 iterations opens fine in Chimera. The volume after 30 iterations (continued from initial 20 iterations) requires the relion_image_handler trick to open without problem in chimera. Note, this has only occurred for one 3D Class (the first one I opened in Chimera), I haven't checked any others. Thanks!
