### ISSUE TITLE
Have problem with running topaz in Relion 4.0

### ISSUE THREAD

**Issue by haomingzh** [3dem/relion#823]
Hello, We have some problems running topaz within Relion 4.0 and would appreciate your help. We tested Topaz and found it worked fine by itself. But we got the following errors when launching Topaz in Relion4 after providing the absolute path for topaz executable.

# using device=0 with cuda=True
# Loading model: unet
Traceback (most recent call last):
  File "/app/data/topaz-env/bin/topaz", line 11, in <module>
    load_entry_point('topaz-em==0.2.4', 'console_scripts', 'topaz')()
  File "/app/data/topaz-env/lib/python3.6/site-packages/topaz/main.py", line 148, in main
    args.func(args)
  File "/app/data/topaz-env/lib/python3.6/site-packages/topaz/commands/denoise.py", line 540, in main
    mic = np.array(load_image(path), copy=False).astype(np.float32)
  File "/app/data/topaz-env/lib/python3.6/site-packages/topaz/utils/data/loader.py", line 103, in load_image
    image = load_mrc(path, standardize=standardize)
  File "/app/data/topaz-env/lib/python3.6/site-packages/topaz/utils/data/loader.py", line 51, in load_mrc
    image, header, extended_header = mrc.parse(content)
  File "/app/data/topaz-env/lib/python3.6/site-packages/topaz/mrc.py", line 134, in parse
    raise Exception('Unknown dtype mode:' + str(header.model))
AttributeError: 'MRCHeader' object has no attribute 'model'
# using device=0 with cuda=True
# Loading model: unet
Traceback (most recent call last):
  File "/app/data/topaz-env/bin/topaz", line 11, in <module>
    load_entry_point('topaz-em==0.2.4', 'console_scripts', 'topaz')()
  File "/app/data/topaz-env/lib/python3.6/site-packages/topaz/main.py", line 148, in main
    args.func(args)
  File "/app/data/topaz-env/lib/python3.6/site-packages/topaz/commands/denoise.py", line 540, in main
    mic = np.array(load_image(path), copy=False).astype(np.float32)
  File "/app/data/topaz-env/lib/python3.6/site-packages/topaz/utils/data/loader.py", line 103, in load_image
    image = load_mrc(path, standardize=standardize)
  File "/app/data/topaz-env/lib/python3.6/site-packages/topaz/utils/data/loader.py", line 51, in load_mrc
    image, header, extended_header = mrc.parse(content)
  File "/app/data/topaz-env/lib/python3.6/site-packages/topaz/mrc.py", line 134, in parse
    raise Exception('Unknown dtype mode:' + str(header.model))
AttributeError: 'MRCHeader' object has no attribute 'model'

**Comment by biochem-fan** [comment]
You need the latest code of Topaz from their GitHub.
https://github.com/tbepler/topaz

This bug was repaired in https://github.com/tbepler/topaz/commit/77f983192d05df7a3fe671d291ecbbc97c232b15.
