### ISSUE TITLE
resizeHostCopy: Array resized to size zero (permitted with fear)

### ISSUE THREAD

**Issue by xizhihui** [3dem/relion#885]
**Describe your problem**
 I follow the 2D classification in Reference-free 2D class averaging from relion4.0 tutorial on my own data. 
 In iteration 56 of 100, I got the  `DEBUG ERROR: deviceAlloc called with size == 0`. 

**Environment:**
 - OS: [Ubuntu 16.04 LTS]
 - MPI runtime: [OpenMPI 4.1.3]
 - RELION version [RELION-4.0-beta-2-commit-9b23e5]
 - Memory: [377GB]
 - GPU: [GTX 3090]

**Dataset:**
 - Box size: [336 pix]
 - Pixel size: [1.5 Å/px]
 - Number of particles: [107524]
 - Description: [e.g. A tetrameric protein of about 400 kDa in total]

**Job options:**
 - Type of job: [ Class2D ]
 - Number of MPI processes: [1]
 - Number of threads: [8]
 - Full command (see `note.txt` in the job directory):
```shell
`which relion_refine` --o Class2D/job018_opgpu/run --iter 100 --i Extract/job017/particles.star --dont_combine_weights_via_disc --pool 3 --pad 2 --ctf --tau2_fudge 2 --particle_diameter 224 --K 50 --flatten_solvent --zero_mask --center_classes --oversampling 1 --psi_step 12 --offset_range 5 --offset_step 2 --norm --scale --j 8 --gpu 0 --free_gpu_memory 2048 --pipeline_control Class2D/job018_opgpu
```

**Error message:**

I ran the command above directly in the command line by myself.

```
Auto-refine: Estimated accuracy angles= 0.78 degrees; offsets= 0.345 Angstroms
CurrentResolution= 5.19588 Angstroms, which requires orientationSampling of at least 2.64706 degrees for a particle of diameter 224 Angstroms
Oversampling= 0 NrHiddenVariableSamplingPoints= 33600
OrientationalSampling= 11.25 NrOrientations= 32
TranslationalSampling= 3 NrTranslations= 21
=============================
Oversampling= 1 NrHiddenVariableSamplingPoints= 1075200
OrientationalSampling= 5.625 NrOrientations= 256
TranslationalSampling= 1.5 NrTranslations= 84
=============================
POSSIBLE ISSUE: resizeHostCopy: Array resized to size zero (permitted with fear).  Something may break downstream
in /home/xizhihui/biosoft/013_protein_structure/backup/relion/src/acc/acc_ptr.h:450
DEBUG: Total GPU allocation size set to 21353 MB on device id 0.
DEBUG ERROR: deviceAlloc called with size == 0 in /path/to/relion/src/acc/acc_ptr.h:311
run_class2d_job018_gpu.sh: 行 7: 14110 段错误               (核心已转储) 
==================
```
Thanks for your help!
Best regards

**Comment by biochem-fan** [comment]
I haven't seen this before...

Is this reproducible? Does this happen if you run the job again?

**Comment by xizhihui** [comment]
Hi, fan
Result  was OK after reran.  It's weird.

**Comment by xizhihui** [comment]
@biochem-fan sorry to bother you. 
I got a new error after I ran the select good particles(in previous step, I manually picked).  After search the [torch issue](https://github.com/pytorch/pytorch/issues/77840), I thought this error was from different torch-version between model generated and my local( version=1.11.0+cu113). 
So could you tell me the torch version used to generate "relion_class_ranker_default_model.pt" ? 

**Command**
```
`which relion_class_ranker` --opt Class2D/job018/run_it100_optimiser.star --o Select/job019/ --fn_sel_parts particles.star --fn_sel_classavgs class_averages.star --python /opt/proteins/python/3.8.8/bin/python --fn_root rank --do_granularity_features  --auto_select  --min_score 0.25  --pipeline_control Select/job019/
```
**Error message**
```
 Initialising...
Using default pytorch model: /opt/proteins/relion/op4.0_gpu_debug/bin/relion_class_ranker_default_model.pt
Using python script: /opt/proteins/relion/op4.0_gpu_debug/bin/relion_class_ranker.py
 Calculating features for each class ...
  29/  29 sec ............................................................~~(,_,">
 Deploying torch model for each class ...
Traceback (most recent call last):
  File "/opt/proteins/relion/op4.0_gpu_debug/bin/relion_class_ranker.py", line 28, in <module>
    model = torch.jit.load(model_fn)
  File "/opt/proteins/python/3.8.8/lib/python3.8/site-packages/torch/jit/_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: Legacy model format is not supported on mobile.

in: /home/xizhihui/biosoft/013_protein_structure/backup/relion/src/class_ranker.cpp, line 1933
ERROR:
Failed to run external python script with the following command:
 /opt/proteins/python/3.8.8/bin/python /opt/proteins/relion/op4.0_gpu_debug/bin/relion_class_ranker.py /opt/proteins/relion/op4.0_gpu_debug/bin/relion_class_ranker_default_model.pt Select/job019/
=== Backtrace  ===
/opt/proteins/relion/op4.0_gpu_debug/bin/relion_class_ranker(_ZN11RelionErrorC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_l+0x7b) [0x55a0fb]
/opt/proteins/relion/op4.0_gpu_debug/bin/relion_class_ranker(_ZN11ClassRanker16deployTorchModelER8FileNameRSt6vectorIfSaIfEES5_S5_+0x676) [0x530724]
/opt/proteins/relion/op4.0_gpu_debug/bin/relion_class_ranker(_ZN11ClassRanker14performRankingEv+0x521) [0x531041]
/opt/proteins/relion/op4.0_gpu_debug/bin/relion_class_ranker(_ZN11ClassRanker3runEv+0x5c) [0x527cc2]
/opt/proteins/relion/op4.0_gpu_debug/bin/relion_class_ranker(main+0x67) [0x4e24c6]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f399a094840]
/opt/proteins/relion/op4.0_gpu_debug/bin/relion_class_ranker(_start+0x29) [0x4e1e19]
==================
ERROR:
Failed to run external python script with the following command:
 /opt/proteins/python/3.8.8/bin/python /opt/proteins/relion/op4.0_gpu_debug/bin/relion_class_ranker.py /opt/proteins/relion/op4.0_gpu_debug/bin/relion_class_ranker_default_model.pt Select/job019/

 RELION version: 4.0-beta-2-commit-9b23e5
 exiting with an error ...
```

**Comment by zxt-triumph** [comment]
I also encountered this problem that RuntimeError: Legacy model format is not supported on mobile.
How do you solve this problem?
Looking forward to your reply.

**Comment by xizhihui** [comment]
@zxt-triumph 
Maybe you should check your torch version
```
pip3 install torch==1.8.2 torchvision==0.9.2 torchaudio==0.8.2 --extra-index-url https://download.pytorch.org/whl/lts/1.8/cu111
```
