### ISSUE TITLE
"Broken" Volumes with Class3D

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#95]
Originally reported by: **AndreHeuer (Bitbucket: [Xenoprime](https://bitbucket.org/Xenoprime), GitHub: [Xenoprime](https://github.com/Xenoprime))**

----------------------------------------

While analyzing the output of several Class3D runs we have found that sometimes the output volumes cannot be read in chimera. Relion shows no errors and proceeds as expected. 

Using the relion_display tool, we can display slices of the volumes. Also we can convert these volumes to spider format and then display these in chimera. This seems to indicate that the volume data itself is fine, perhaps only the header is broken or incompatible with chimera?

This has so far occurred in two classification runs and then all (tested) output volumes were "broken". 

We do not really know how to approach this problem as it only seems to occur sporadically but we will happily provide further information.

The error displayed by chimera:
/opt/UCSF/Chimera64-1.11.1rc/share/VolumeViewer/volume.py:1448: RuntimeWarning: invalid value encountered in double_scalars
  tf = ((xi-xo, xj-xo, xk-xo, xo),
/opt/UCSF/Chimera64-1.11.1rc/share/VolumeViewer/volume.py:1449: RuntimeWarning: invalid value encountered in double_scalars
  (yi-yo, yj-yo, yk-yo, yo),
/opt/UCSF/Chimera64-1.11.1rc/share/VolumeViewer/volume.py:1450: RuntimeWarning: invalid value encountered in double_scalars
  (zi-zo, zj-zo, zk-zo, zo))
/opt/UCSF/Chimera64-1.11.1rc/share/VolumeViewer/volume.py:2601: RuntimeWarning: invalid value encountered in double_scalars
  dx, dy, dz = map(lambda a, b: a-b, xyz1, xyz2)
Traceback (most recent call last):
  File "/opt/UCSF/Chimera64-1.11.1rc/share/chimera/triggerSet.py", line 83, in invoke
    self._funcData, triggerData)
  File "/opt/UCSF/Chimera64-1.11.1rc/share/VolumeViewer/volume.py", line 63, in open_models_cb
    self.add_volumes(vlist)
  File "/opt/UCSF/Chimera64-1.11.1rc/share/VolumeViewer/volume.py", line 82, in add_volumes
    cb(vlist)
  File "/opt/UCSF/Chimera64-1.11.1rc/share/VolumeViewer/volumedialog.py", line 257, in volume_opened_cb
    self.display_region_info(v)
  File "/opt/UCSF/Chimera64-1.11.1rc/share/VolumeViewer/volumedialog.py", line 325, in display_region_info
    p.update_panel_widgets(data_region)
  File "/opt/UCSF/Chimera64-1.11.1rc/share/VolumeViewer/volumedialog.py", line 3288, in update_panel_widgets
    self.set_zone_radius_slider_range(data_region)
  File "/opt/UCSF/Chimera64-1.11.1rc/share/VolumeViewer/volumedialog.py", line 3412, in set_zone_radius_slider_range
    self.zone_radius.set_range(0, r, step)
  File "/opt/UCSF/Chimera64-1.11.1rc/share/CGLtk/Hybrid.py", line 732, in set_range
    s['resolution'] = step
  File "/opt/UCSF/Chimera64-1.11.1rc/lib/python2.7/lib-tk/Tkinter.py", line 1335, in __setitem__
    self.configure({key: value})
  File "/opt/UCSF/Chimera64-1.11.1rc/lib/python2.7/lib-tk/Tkinter.py", line 1328, in configure
    return self._configure('configure', cnf, kw)
  File "/opt/UCSF/Chimera64-1.11.1rc/lib/python2.7/lib-tk/Tkinter.py", line 1319, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
TclError: floating point value is Not a Number
Error processing trigger "addModel":
TclError: floating point value is Not a Number

  File "/opt/UCSF/Chimera64-1.11.1rc/lib/python2.7/lib-tk/Tkinter.py", line 1319, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf)) 

----------------------------------------
- Bitbucket: https://bitbucket.org/tcblab/relion2-beta/issue/95

**Comment by bforsbe** [comment]
This issue should be fixed in v2.0.4, which only sets the corrupt header fields if they are finite. The fields which are "corrupt" are only in the mrc header (i.e. the volume-data is NOT corrupt), and not used by relion. The issue of persistence of corrupt volumes and their effect on the chimera environment in general has also been noted to the chimera development team.
